# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:09:16+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Header, Query, UploadFile

from models import (
    FeedType,
    V3CppreferencePostRequest,
    V3CppreferencePostResponse,
    V3FeedsPostResponse,
    V3PricePutRequest,
    V3PricePutResponse,
)

app = MCPProxy(
    contact={'x-twitter': 'Walmart'},
    description='The price is a fundamental building block for your listing on Walmart.com. You can use the price management APIs to set up and manage the price for a given item',
    title='Price Management',
    version='1.0.0',
    servers=[
        {'description': 'Production URL', 'url': 'https://marketplace.walmartapis.com'},
        {'description': 'Sandbox URL', 'url': 'https://sandbox.walmartapis.com'},
    ],
)


@app.post(
    '/v3/cppreference',
    description=""" This API helps Sellers to completely opt-in or opt-out from CAP program.

If the subsidyEnrolled value = "true", the Seller enrolls in the CAP program. All eligible SKUs (current and future) are by default opt-in. Seller should use the SKU opt-in/opt-out API to opt-out individual items.

If the subsidyEnrolled value = "false", the Seller stops participating in the CAP program and all eligible SKUs (current and future) are opt-out of the CAP program. """,
    tags=['price_setting_operations'],
    security=[],
)
def opt_cap_program_in_price(
    w_m__s_e_c__a_c_c_e_s_s__t_o_k_e_n: str = Header(..., alias='WM_SEC.ACCESS_TOKEN'),
    w_m__c_o_n_s_u_m_e_r__c_h_a_n_n_e_l__t_y_p_e: Optional[str] = Header(
        None, alias='WM_CONSUMER.CHANNEL.TYPE'
    ),
    w_m__q_o_s__c_o_r_r_e_l_a_t_i_o_n__i_d: str = Header(
        ..., alias='WM_QOS.CORRELATION_ID'
    ),
    w_m__s_v_c__n_a_m_e: str = Header(..., alias='WM_SVC.NAME'),
    body: V3CppreferencePostRequest = ...,
):
    """
    Set up CAP SKU All
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v3/feeds',
    description=""" Updates prices in bulk.

In one Feed you can update up to 10,000 items in bulk. To ensure optimal Feed processing time, we recommend sending no more than 1000 items in one Feed and keeping the Feed sizes below 10 MB.

The price sequence guarantee is observed by the bulk price update functionality, subject to the following rules:

The timestamp used to determine precedence is passed in the request headers. All price updates in the feed are considered to have the same timestamp. The timestamp in the XML file is used only for auditing.
You can send a single SKU multiple times in one Feed. If a SKU is repeated in a Feed, the price will be set for that SKU on Walmart.com, but there is no guarantee as to which SKU's price within that feed will be used.
This API should be used in preference to the update a price. It should be called no sooner than 24 hours after a new item is set up and a wpid (Walmart Part ID) is available. Thereafter, the bulk price update has an service level agreement (SLA) of 15 minutes.

After the update is submitted, wait for at least five minutes before verifying whether the bulk price update was successful. Individual SKU price update success or failure is only available after the entire feed is processed.

If a SKU's price update fails (for example, multiple price updates were sent for the same SKU in a single feed), an error will be returned. """,
    tags=['price_setting_operations'],
    security=[],
)
def price_bulk_uploads(
    feed_type: FeedType = Query(..., alias='feedType'),
    w_m__s_e_c__a_c_c_e_s_s__t_o_k_e_n: str = Header(..., alias='WM_SEC.ACCESS_TOKEN'),
    w_m__c_o_n_s_u_m_e_r__c_h_a_n_n_e_l__t_y_p_e: Optional[str] = Header(
        None, alias='WM_CONSUMER.CHANNEL.TYPE'
    ),
    w_m__q_o_s__c_o_r_r_e_l_a_t_i_o_n__i_d: str = Header(
        ..., alias='WM_QOS.CORRELATION_ID'
    ),
    w_m__s_v_c__n_a_m_e: str = Header(..., alias='WM_SVC.NAME'),
    file: UploadFile = ...,
):
    """
    Update bulk prices (Multiple)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/v3/price',
    description=""" Updates the regular price for a given item. """,
    tags=['price_setting_operations'],
    security=[],
)
def update_price(
    w_m__s_e_c__a_c_c_e_s_s__t_o_k_e_n: str = Header(..., alias='WM_SEC.ACCESS_TOKEN'),
    w_m__c_o_n_s_u_m_e_r__c_h_a_n_n_e_l__t_y_p_e: Optional[str] = Header(
        None, alias='WM_CONSUMER.CHANNEL.TYPE'
    ),
    w_m__q_o_s__c_o_r_r_e_l_a_t_i_o_n__i_d: str = Header(
        ..., alias='WM_QOS.CORRELATION_ID'
    ),
    w_m__s_v_c__n_a_m_e: str = Header(..., alias='WM_SVC.NAME'),
    body: V3PricePutRequest = ...,
):
    """
    Update a price
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
